fixing condition of failure

diff --git a/.github/workflows/sandboxStartCreation.yml b/.github/workflows/sandboxStartCreation.yml
--- a/.github/workflows/sandboxStartCreation.yml
+++ b/.github/workflows/sandboxStartCreation.yml
@@ -45,6 +45,8 @@ jobs:
 
       - name: Check exit code to confirm successful call
         id: check
-        if: ${{ steps.create.outputs.exitcode }} != 68
-        run: exit 1
+        if: ${{ steps.create.outputs.exitcode != 68 }} 
+        run: |
+          echo "Error on sandbox creation - please check the results of the last step."
+          exit 1
 
